version: "3.9"

services:
  redis:
    image: "redis:alpine"

  flask:
    image: flask
    restart: always
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 0:80:5000
