version: "3.9"

services:
  redis:
    image: "redis:alpine"

  fastapi:
    image: fastapi
    build: .
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 0:80:80